language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '8'
after_success:
  - yarn run travis-deploy-once "yarn run semantic-release"
  - yarn run coverage
  
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
